{% set name = "katex" %}
{% set version = "0.16.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/KaTeX/KaTeX/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 85a72e01c954ab6f600f291b27f8af5f1310bd841c8a3fa0c9467e48913c2acc

  - url: https://github.com/KaTeX/KaTeX/releases/download/v{{ version }}/katex.tar.gz
    sha256: eced495f02ee6a3cc9044a81c8e1be7fe339d5365525ddd499d7599fe33ed8a9
    folder: dist

build:
  number: 0
  noarch: generic
  script:
    - tgz=$(npm pack)
    - npm install -g $tgz

requirements:
  host:
    - nodejs
  run:
    - nodejs
    - __unix

test:
  commands:
    - test -f $PREFIX/bin/katex
    - katex --version

about:
  home: https://github.com/KaTeX/KaTeX
  license: MIT
  license_file: LICENSE
  summary: Fast math typesetting for the web.

extra:
  recipe-maintainers:
    - isuruf
