{% set name = "katex" %}
{% set version = "0.16.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/KaTeX/KaTeX/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 9f981dad36c339b6e85ee1293d4f74a405b894dbff2f314d1fd9f1d0db03f957

  - url: https://github.com/KaTeX/KaTeX/releases/download/v{{ version }}/katex.tar.gz
    sha256: c57485ad08cbd31366f80d722dcfc9c29c5e58df49b0e3621c9187c36665af9b
    folder: dist

build:
  number: 0
  noarch: generic
  script:
    - tgz=$(npm pack)
    - npm install -g $tgz

requirements:
  host:
    - nodejs
  run:
    - nodejs
    - __unix

test:
  commands:
    - test -f $PREFIX/bin/katex
    - katex --version

about:
  home: https://github.com/KaTeX/KaTeX
  license: MIT
  license_file: LICENSE
  summary: Fast math typesetting for the web.

extra:
  recipe-maintainers:
    - isuruf
