{% set name = "katex" %}
{% set version = "0.16.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/KaTeX/KaTeX/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 76f4b1aa1ce86bc467b941923e01ba4907ff6e2c0c36eb6642129cdf3ef70d46

  - url: https://github.com/KaTeX/KaTeX/releases/download/v{{ version }}/katex.tar.gz
    sha256: b968d389d7b9455e191605e4984c52faf3123213271880b02abc45e6ad4bbf43
    folder: dist

build:
  number: 0
  noarch: generic
  script:
    - tgz=$(npm pack)
    - npm install -g $tgz

requirements:
  host:
    - nodejs
  run:
    - nodejs
    - __unix

test:
  commands:
    - test -f $PREFIX/bin/katex
    - katex --version

about:
  home: https://github.com/KaTeX/KaTeX
  license: MIT
  license_file: LICENSE
  summary: Fast math typesetting for the web.

extra:
  recipe-maintainers:
    - isuruf
